const drinksSheet = [
  {
    producto: "Baggio 1L x8",
    $: 2080,
    uni: 8,
    "$ / uni": 260,
    "( $ / uni ) + 30 %": 338,
    price: 350,
    name: "Baggio 1 L",
    outOfStock: false,
    imgUrl: "/img/bebidas/baggio.jpg",
  },
  {
    producto: "Brahma x12",
    $: 5600,
    uni: 12,
    "$ / uni": 466.6666667,
    "( $ / uni ) + 30 %": 606.6666667,
    price: 600,
  },
  {
    producto: "Coca cola 2L 1/4 x8",
    $: 3800,
    uni: 8,
    "$ / uni": 475,
    "( $ / uni ) + 30 %": 617.5,
    price: 620,
    name: "Coca Cola 2 ¹⁄₄ L",
    outOfStock: false,
    imgUrl: "/img/bebidas/coca-cola.jpg",
  },
  {
    producto: "Coca vidrio x12",
    $: 3300,
    uni: 12,
    "$ / uni": 275,
    "( $ / uni ) + 30 %": 357.5,
    price: 350,
  },
  {
    producto: "Cosecha tardía bco",
    $: 3550,
    uni: 6,
    "$ / uni": 591.6666667,
    "( $ / uni ) + 30 %": 769.1666667,
    price: 800,
    name: "Cosecha Tardía",
    outOfStock: false,
    imgUrl: "/img/bebidas/cosecha-tardia.jpg",
  },
  {
    producto: "Dr. Lemon 1L",
    $: 4610,
    uni: 12,
    "$ / uni": 384.1666667,
    "( $ / uni ) + 30 %": 499.4166667,
    price: 530,
    name: "Dr. Lemon 1 L",
    outOfStock: false,
    imgUrl: "/img/bebidas/dr-lemon.jpg",
  },
  {
    producto: "Federico de alvear",
    $: 4800,
    uni: 6,
    "$ / uni": 800,
    "( $ / uni ) + 30 %": 1040,
    price: 1040,
    name: "Federico de Alvear",
    outOfStock: false,
    imgUrl: "/img/bebidas/federico-de-alvear.jpg",
  },
  {
    producto: "Fernet Branca 1L",
    $: 2490,
    uni: 1,
    "$ / uni": 2490,
    "( $ / uni ) + 30 %": 3237,
    price: 3230,
    name: "Fernet Branca 1 L",
    outOfStock: false,
    imgUrl: "/img/bebidas/fernet-branca.jpg",
  },
  {
    producto: "Fernet Branca 3/4",
    $: 1910,
    uni: 1,
    "$ / uni": 1910,
    "( $ / uni ) + 30 %": 2483,
    price: 2480,
    name: "Fernet Branca 3/4 L",
    outOfStock: false,
    imgUrl: "/img/bebidas/fernet-branca.jpg",
  },
  {
    producto: "Fernet branca chico",
    $: 1390,
    uni: 1,
    "$ / uni": 1390,
    "( $ / uni ) + 30 %": 1807,
    price: 1800,
    name: "Fernet branca chico",
    outOfStock: false,
    imgUrl: "/img/bebidas/fernet-branca.jpg",
  },
  {
    producto: "Frizze 1L",
    $: 420,
    uni: 1,
    "$ / uni": 420,
    "( $ / uni ) + 30 %": 546,
    price: 550,
    name: "Frizze 1 L",
    outOfStock: false,
    imgUrl: "/img/bebidas/frizze-blue.jpg",
  },
  {
    producto: "Gancia 950 ml",
    $: 670,
    uni: 1,
    "$ / uni": 670,
    "( $ / uni ) + 30 %": 871,
    price: 900,
    name: "Gancia 950 ml",
    outOfStock: false,
    imgUrl: "/img/bebidas/gancia.jpg",
  },
  {
    producto: "Jugo rinde dos",
    $: 1060,
    uni: 1,
    "$ / uni": 1060,
    "( $ / uni ) + 30 %": 1378,
    price: 90,
  },
  {
    producto: "Latas Brahma",
    $: 5800,
    uni: 24,
    "$ / uni": 241.6666667,
    "( $ / uni ) + 30 %": 314.1666667,
    price: 320,
    name: "Latas Brahma",
    outOfStock: false,
    imgUrl: "/img/bebidas/latas-brahma.jpg",
  },
  {
    producto: "Laton 710 miller",
    $: 3000,
    uni: 6,
    "$ / uni": 500,
    "( $ / uni ) + 30 %": 650,
    price: 650,
    name: "Laton  Miller 710 ml",
    outOfStock: false,
    imgUrl: "/img/bebidas/laton-miller.jpg",
  },
  {
    producto: "Licor Cusenier",
    $: 880,
    uni: 1,
    "$ / uni": 880,
    "( $ / uni ) + 30 %": 1144,
    price: 1150,
    name: "Licor Cusenier",
    outOfStock: false,
  },
  {
    producto: "Manaos 2,25 x6",
    $: 1140,
    uni: 6,
    "$ / uni": 190,
    "( $ / uni ) + 30 %": 247,
    price: 240,
    name: "Manaos 2,25 ml",
    outOfStock: false,
    imgUrl: "/img/bebidas//manaos.jpg",
  },
  {
    producto: "Master común de 20",
    $: 2720,
    "$ / uni": "#DIV/0!",
    "( $ / uni ) + 30 %": "#DIV/0!",
    price: 280,
  },
  {
    producto: "Patero S.Filomena",
    $: 3400,
    uni: 6,
    "$ / uni": 566.6666667,
    "( $ / uni ) + 30 %": 736.6666667,
    price: 730,
    name: "Patero S.Filomena",
    outOfStock: false,
    imgUrl: "/img/bebidas/vino-santa-filomena.jpg",
  },
  {
    producto: "Pet criadores",
    $: 5000,
    uni: 12,
    "$ / uni": 416.6666667,
    "( $ / uni ) + 30 %": 541.6666667,
    price: 550,
    name: "Petaca criadores",
    outOfStock: false,
    imgUrl: "/img/bebidas/petaca-criadores.jpg",
  },
  {
    producto: "Petaca cusenier café.c",
    $: 320,
    uni: 1,
    "$ / uni": 320,
    "( $ / uni ) + 30 %": 416,
    price: 500,
    name: "Petaca cusenier café o menta",
    outOfStock: false,
    imgUrl: "/img/bebidas/petaca-cusenier.jpg",
  },
  {
    producto: "Placer 1,5 / 500",
    $: 910,
    uni: 6,
    "$ / uni": 151.6666667,
    "( $ / uni ) + 30 %": 197.1666667,
    price: 200,
    name: "Placer 1,5 L",
    outOfStock: false,
    imgUrl: "/img/bebidas/placer.jpg",
  },
  {
    producto: "Red point común de 20",
    $: 2790,
    "$ / uni": "#DIV/0!",
    "( $ / uni ) + 30 %": "#DIV/0!",
    price: 400,
  },
  {
    producto: "Smirnoff Saborizado",
    $: 1370,
    uni: 1,
    "$ / uni": 1370,
    "( $ / uni ) + 30 %": 1781,
    price: 1780,
    name: "Smirnoff Saborizado",
    outOfStock: false,
    imgUrl: "/img/bebidas/smirnoff.jpg",
  },
  {
    producto: "SPEED 473 XL",
    $: 3300,
    uni: 12,
    "$ / uni": 275,
    "( $ / uni ) + 30 %": 357.5,
    price: 360,
    name: "SPEED XL",
    outOfStock: false,
    imgUrl: "/img/bebidas/speed.jpg",
  },
  {
    producto: "Viñas Alvear 1,25",
    $: 4200,
    uni: 6,
    "$ / uni": 700,
    "( $ / uni ) + 30 %": 910,
    price: 900,
    name: "Viñas Alvear 1,25 L",
    outOfStock: false,
    imgUrl: "/img/bebidas/viñas-de-alvear.jpg",
  },
  {
    producto: "Viñas Balbo",
    $: 2930,
    uni: 6,
    "$ / uni": 488.3333333,
    "( $ / uni ) + 30 %": 634.8333333,
    price: 630,
    name: "Viñas Balbo",
    outOfStock: false,
    imgUrl: "/img/bebidas/viñas-de-balbo.jpg",
  },
];

function extractProperties(array) {
  const result = [];
  for (let i = 0; i < array.length; i++) {
    const { name, price, imgUrl, outOfStock } = array[i];
    if (name !== undefined) {
      result.push({ name, price, imgUrl: imgUrl || null, outOfStock });
    }
  }
  return result;
}

export const productsObj = {
  escabio: extractProperties(drinksSheet),
  helados: [
    {
      name: "1 kg",
      imgUrl: "/img/helados/kilo.jpg",
      price: 1200,

      flavours: 4,
    },
    {
      name: "1/2 kg",
      imgUrl: "/img/helados/medio.jpg",
      price: 800,

      flavours: 3,
    },
    {
      name: "1/4 kg",
      imgUrl: "/img/helados/cuarto.jpg",
      price: 800,

      flavours: 2,
    },
  ],
};
